"""casting_transaction_datetime_to_timestamp

Revision ID: 37f8690dc83f
Revises: d8e65d29c60b
Create Date: 2025-05-26 11:48:59.206666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37f8690dc83f'
down_revision: Union[str, None] = 'd8e65d29c60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               server_default=sa.func.now(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
